### ISSUE TITLE
params and flops of the model

### ISSUE THREAD

**Issue by HitBadTrap** [polo5/LDEQ_RwR#4]
你好！我对这篇工作十分感兴趣，想在自己的文章中引用，利用你提供框架，我测得的params=21.812 M，flops=138.593 GMac，请问是否与你测得的相一致呢？
![3185687e0c8b20a21cc30e69eded69d](https://github.com/polo5/LDEQ_RwR/assets/113753579/4c8e72be-6f15-405d-b7b6-dd78a288925e)
这是测试的代码，其他的设置使用的是repo里默认的参数

**Comment by polo5** [comment]
Sorry I don't read mandarin, but based on what I can understand the parameter count (21.8M) is indeed what was reported in our paper [here](https://openaccess.thecvf.com/content/CVPR2023/papers/Micaelli_Recurrence_Without_Recurrence_Stable_Video_Landmark_Detection_With_Deep_Equilibrium_CVPR_2023_paper.pdf). For the flops I would be very careful to report any value, because DEQ models are adaptive, and so different inputs/root solvers will result in different flop values.
